### ISSUE TITLE
GetMetricStatistics not returning result. None of the logging examples will compile, so ...

### ISSUE THREAD

**Issue by kcrossen** [aws/aws-sdk-cpp#1109]
### What platform/OS are you using?
OSX 10.11.6

### What compiler are you using? what version?
Qt Creator
### Can you provide a TRACE level log? (sanitize any sensitive information)
Followed installation directions exactly, latest everything:
https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/setup.html
I built static libraries for core and monitoring.

I've tried every single logging example I have found and none of them will even compile. 

```
#include <QtCore>

#include "CW_Remote.h"

#include <aws/core/Aws.h>
#include <aws/core/utils/logging/AWSLogging.h>
#include <aws/core/utils/logging/DefaultLogSystem.h>

#include <aws/core/client/ClientConfiguration.h>
#include <aws/core/auth/AWSCredentials.h>
#include <aws/core/Region.h>

#include <aws/monitoring/CloudWatchClient.h>
#include <aws/monitoring/CloudWatchEndpoint.h>
#include <aws/monitoring/CloudWatchRequest.h>
#include <aws/monitoring/model/GetMetricStatisticsRequest.h>
#include <aws/monitoring/model/GetMetricStatisticsResult.h>

using namespace Aws;
using namespace Aws::Auth;
using namespace Aws::CloudWatch;

int main ( /* int argc, char* argv[] */ )
{  
    SDKOptions options;
    options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
    InitAPI(options);

    AWSCredentials credentials;
    credentials.SetAWSAccessKeyId("xxx");
    credentials.SetAWSSecretKey("yyy");

    Aws::Client::ClientConfiguration client_configuration;
    client_configuration.region = "us-east-1";
    client_configuration.scheme = Aws::Http::Scheme::HTTPS;
    client_configuration.connectTimeoutMs = 30000;
    client_configuration.requestTimeoutMs = 120000;

    Aws::CloudWatch::CloudWatchClient cloudwatch_client(credentials, client_configuration);

    Aws::String endpoint = Aws::CloudWatch::CloudWatchEndpoint::ForRegion("us-east-1");

    Aws::CloudWatch::Model::GetMetricStatisticsRequest request;
    Aws::CloudWatch::Model::Dimension request_dimension;

    request.SetMetricName("CPUUtilization");
    request.SetNamespace("AWS/RDS");

    request_dimension.SetName("DBInstanceIdentifier");
    request_dimension.SetValue("prod-stories-master");
    request.AddDimensions(request_dimension);

    request.SetStartTime(Aws::Utils::DateTime((char*)"2019-04-03T06:30:00Z",
                                              Aws::Utils::DateFormat::ISO_8601));
    request.SetEndTime(Aws::Utils::DateTime((char*)"2019-04-04T06:30:00Z",
                                            Aws::Utils::DateFormat::ISO_8601));
    request.SetPeriod(60);

    request.AddStatistics(Aws::CloudWatch::Model::Statistic::Average);
    request.AddStatistics(Aws::CloudWatch::Model::Statistic::Maximum);

    request.SetUnit(Aws::CloudWatch::Model::StandardUnit::Percent);

    Aws::CloudWatch::Model::GetMetricStatisticsOutcome raw_metric_statistics =
        cloudwatch_client.GetMetricStatistics(request);

    Aws::Utils::Logging::ShutdownAWSLogging();

    ShutdownAPI(options);
}
```
This is what comes back:
```
	Locals		
		[statics]		
		client_configuration		Aws::Client::ClientConfiguration
		cloudwatch_client		Aws::CloudWatch::CloudWatchClient
		credentials		Aws::Auth::AWSCredentials
		endpoint	"monitoring.us-east-1.amazonaws.com"	Aws::String
		options		Aws::SDKOptions
		raw_metric_statistics		Aws::CloudWatch::Model::GetMetricStatisticsOutcome
		request		Aws::CloudWatch::Model::GetMetricStatisticsRequest
		request_dimension		Aws::CloudWatch::Model::Dimension
	Inspector		
	Expressions		
	Return Value		
	Tooltip		
```
and
```
	Locals		
		[statics]		
		client_configuration		Aws::Client::ClientConfiguration
		cloudwatch_client		Aws::CloudWatch::CloudWatchClient
		credentials		Aws::Auth::AWSCredentials
		endpoint	"monitoring.us-east-1.amazonaws.com"	Aws::String
		options		Aws::SDKOptions
		raw_metric_statistics		Aws::CloudWatch::Model::GetMetricStatisticsOutcome
			error	@0x7fff5fbff0f0	Aws::Client::AWSError<Aws::CloudWatch::CloudWatchErrors>
				m_errorType	NETWORK_CONNECTION	Aws::CloudWatch::CloudWatchErrors
				m_exceptionName	""	Aws::String
				m_isRetryable	true	bool
				m_message	"Unable to connect to endpoint"	Aws::String
				m_responseCode	1606409952	Aws::Http::HttpResponseCode
				m_responseHeaders	<0 items>	Aws::Http::HeaderValueCollection
			result	@0x7fff5fbff0a0	Aws::CloudWatch::Model::GetMetricStatisticsResult
			success	false	bool
		request		Aws::CloudWatch::Model::GetMetricStatisticsRequest
		request_dimension		Aws::CloudWatch::Model::Dimension
	Inspector		
	Expressions		
	Return Value		
	Tooltip		
```
Analogous code in Python/boto3 works perfectly.

**Comment by singku** [comment]
What do you mean by "None of the logging examples will compile"? Are you refer to the examples here? https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/cpp/example_code/cloudwatch

> This is what comes back

Are those what the debugger showed?

As you can see that there is an error message "Unable to connect to endpoint", means the request was not send correctly. Check the endpoint you were hitting, the credentials you used and your network connection.

Try the following with your real key and secrete_key
```
#include <QtCore>

#include "CW_Remote.h"

#include <aws/core/Aws.h>
#include <aws/core/utils/logging/AWSLogging.h>
#include <aws/core/utils/logging/DefaultLogSystem.h>

#include <aws/core/client/ClientConfiguration.h>
#include <aws/core/auth/AWSCredentials.h>
#include <aws/core/Region.h>

#include <aws/monitoring/CloudWatchClient.h>
#include <aws/monitoring/CloudWatchEndpoint.h>
#include <aws/monitoring/CloudWatchRequest.h>
#include <aws/monitoring/model/GetMetricStatisticsRequest.h>
#include <aws/monitoring/model/GetMetricStatisticsResult.h>

using namespace Aws;
using namespace Aws::Auth;
using namespace Aws::CloudWatch;

int main ( /* int argc, char* argv[] */ )
{  
    SDKOptions options;
    options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
    InitAPI(options);
++ {
    AWSCredentials credentials;
++credentials.SetAWSAccessKeyId(YOUR_REAL_KEY); 
++credentials.SetAWSSecretKey(YOUR_REAL_SECRET_KEY);

    Aws::Client::ClientConfiguration client_configuration;
-- client_configuration.region = "us-east-1";
-- client_configuration.scheme = Aws::Http::Scheme::HTTPS;
    client_configuration.connectTimeoutMs = 30000;
    client_configuration.requestTimeoutMs = 120000;

    Aws::CloudWatch::CloudWatchClient cloudwatch_client(credentials, client_configuration);

-- Aws::String endpoint = Aws::CloudWatch::CloudWatchEndpoint::ForRegion("us-east-1");

    Aws::CloudWatch::Model::GetMetricStatisticsRequest request;
    Aws::CloudWatch::Model::Dimension request_dimension;

    request.SetMetricName("CPUUtilization");
    request.SetNamespace("AWS/RDS");

    request_dimension.SetName("DBInstanceIdentifier");
    request_dimension.SetValue("prod-stories-master");
    request.AddDimensions(request_dimension);

    request.SetStartTime(Aws::Utils::DateTime((char*)"2019-04-03T06:30:00Z",
                                              Aws::Utils::DateFormat::ISO_8601));
    request.SetEndTime(Aws::Utils::DateTime((char*)"2019-04-04T06:30:00Z",
                                            Aws::Utils::DateFormat::ISO_8601));
    request.SetPeriod(60);

    request.AddStatistics(Aws::CloudWatch::Model::Statistic::Average);
    request.AddStatistics(Aws::CloudWatch::Model::Statistic::Maximum);

    request.SetUnit(Aws::CloudWatch::Model::StandardUnit::Percent);

    Aws::CloudWatch::Model::GetMetricStatisticsOutcome raw_metric_statistics =
        cloudwatch_client.GetMetricStatistics(request);

    Aws::Utils::Logging::ShutdownAWSLogging();
++}
    ShutdownAPI(options);
}
```

**Comment by kcrossen** [comment]
Let's try this way:

1. Go to https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/examples-cloudwatch.html
and follow the directions very exactly, setting up the credentials file exactly per directions.

2. Download the example on https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/examples-cloudwatch-get-metrics.html.

3. It comes back with "incomplete signature" error.

I did find a workaround, like so:
`
    AWSCredentials credentials;
    credentials.SetAWSAccessKeyId(aws_access_id.toStdString());
    credentials.SetAWSSecretKey(aws_secret_key.toStdString());

    Aws::Client::ClientConfiguration client_configuration;
    client_configuration.region = region_name.toStdString();
    client_configuration.scheme = Aws::Http::Scheme::HTTPS;
    client_configuration.connectTimeoutMs = 30000;
    client_configuration.requestTimeoutMs = 120000;

    Aws::CloudWatch::CloudWatchClient cloudwatch_client(credentials, client_configuration);
`
the values having been read in from a json file.

I've been using Python/boto/boto3 quite successfully for years and everything worked "right out of the box". I could run example code and it all worked, exactly as published. Now I need to use C++, and it's got a much steeper learning curve. Needlessly, I think. If the examples were tested and working, it would probably save lots of time tracing issues for you all.

If you go to stackexchange, etc. you will find a lot of answers to beginner questions that are essentially RTFM, some deservedly no doubt. But I've noticed that quite a few are the same question over and over, and when investigated, it turns out exactly like my example. The FM is demonstrably wrong.

**Comment by singku** [comment]
First of all, the example works for me. I didn't change anything, just download the sample, build, link, run, get the output.

And
There is a document before the usage of cloud watch.
https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/getting-started.html
The second step is to tell you to set up aws credentials. (Your second revised example uses one of the methods to set up credentials). The best practice is to set .aws/credentials in your home directory.

**Comment by kcrossen** [comment]
Here is my credentails file:
```
~/.aws/credentials on macOS

[default]
aws_access_key_id = xxx
aws_secret_access_key = yyy
```
But as you probably know, this is not enough unless your region is
us-east-1. Otherwise, the example can't work.

Second, you don't have a "virgin" machine, plus you already know all the
tricks.

The key item is that the example doesn't work, can't work, for anybody
testing against any other region, right?

Ken

**Comment by singku** [comment]
Hi Ken 
"us-west-2" works for me as well...
But need some additional code to the example like
```
 Aws::Client::ClientConfiguration config;
 config.region = Aws::Region::US_WEST_2;
 Aws::CloudWatch::CloudWatchClient cw(config);
```
because the default region is us-east-1.

But how the credentials is resolved (explicitly specified in code/ env vars/config file) is not related to what the region is.

**Comment by singku** [comment]
Suppose your credential file inside .aws/credentials is correct. You should be able to run the example code against all regions correctly. At least that what I have tested out.

If it doesn't work for you, could you please set options.logOption.logLevel to be Trace and post the log here?

**Comment by kcrossen** [comment]
I still don't understand how the example code (exactly as posted on the
site) with the example credentials file (exactly as posted on the site) can
possibly figure out that I'm in a european region (for example).

I understand that the developers may think of credentials and regions as
totally separate, but my understanding is that any given set of credentials
can only work in a single region. You could say they were related in the
same fashion as the sdk and curl. A dependency.

I have noticed a lot of posts from folks in "foreign" regions having this
type of issue. It could be a good investment in reducing wear and tear on
both the community and folks like yourself to put a region item in the
credentials file. Not particularly "pure", but quite practical.

Ken

**Comment by singku** [comment]
Credentials is not tied to a specific region. It is usable for all regions.
>I still don't understand how the example code (exactly as posted on the
site) with the example credentials file (exactly as posted on the site) can
possibly figure out that I'm in an european region (for example).

It can't.
Some times it doesn't work purely because of the network problem between your local region and target aws region.

**Comment by kcrossen** [comment]
One of the very cool aspects of the boto3 implementation of the API is that there are "documenting" examples that are complete as posted and work exactly as posted. Since I was using PyCharm, I quite literally copy-pasted one example into PyCharm (after pip install boto3), filled in my credential, region, etc., clicked the run button, and my data came back. The whole process took about 15 minutes the first time and was completely frustration-free.

Every needed item to make the demo run is absolutely explicit, you just have to fill in the placeholders. If you don't, PyCharm will underline the placeholders in red as syntax errors. Qt Creator will do exactly the same in C++, given example source code with placeholders rendered as guaranteed syntax errors.

Having a "hidden" extra step such as the c++ sdk's credentials file may look good to developers but it's less helpful for beginners. Because I'd had some experience using the boto3 implementation, I was able to figure out plan B from your class documentation by analogy. Some beginners may not have, or know about, that option.

**Comment by singku** [comment]
Hi Ken, I agree the document is no as good as cli or boto3. We are working with document team to improve that. But in this case, the example are pretty straight forward. Following the instructions, I didn't see any hidden step. Anyway, the important things are, have you solved the problem? have we answered your questions?

**Comment by kcrossen** [comment]
Coding problem solved a different way. I've said my say about my
experienced hardships and what I think should be done about that. It
appears we agree on that part anyway.

Here's my test code, I took the liberty of clipping off the bottom (which
should not matter), and plugging in the values explicitly that are supplied
via argv in the posted code (also should not matter). Referred to here:
https://sdk.amazonaws.com/cpp/api/0.12.9/de/d53/class_aws_1_1_cloud_watch_1_1_model_1_1_list_metrics_request.html
for
answers.

The credentials file is exactly copy/pasted from aws site, my values
substituted, and put in correct place, with path copy/pasted from aws site.

Just so we're clear, when I release from the breakpoint set here "if (!
outcome.IsSuccess())", the code goes into my setup and executes my
application correctly. I believe this would tend to disprove any
"downstream issue" such as http disfunction, etc.
```

int main ( int argc, char* argv[] ) {


    Aws::SDKOptions options;

    Aws::InitAPI(options);

    {

        Aws::CloudWatch::CloudWatchClient cw;

        Aws::CloudWatch::Model::ListMetricsRequest request;


        request.SetMetricName("CPUUtilization");

        request.SetNamespace("AWS/RDS");


        bool done = false;

        bool header = false;

        while (!done)

        {

            auto outcome = cw.ListMetrics(request);

            const bool outcome_is_success = outcome.IsSuccess();

            const auto outcome_error = outcome.GetError();

            if (!outcome.IsSuccess())

            {

                std::cout << "Failed to list CloudWatch metrics:" <<

                    outcome.GetError().GetMessage() << std::endl;

                break;

            }

            done = true;

        }


    }

    Aws::ShutdownAPI(options);

}


```
Having not been able to get logging working, also a problem with the
supplied aws site directions. Where exactly are these logs? They should
give exact directions for finding the logs that an intelligent 16yo could
follow. So here's the debug output from Qt Creator 4.8.2.
```
﻿﻿ Locals
Application @0x7fff5fbfef68 QApplication
MainWindow @0x7fff5fbfeb28 CW_Remote
[statics]
argc 1 int
argv <1 items> char **
aws_access_id @0x7fff5fbfeee8 QString
aws_secret_key @0x7fff5fbfeec0 QString
client_configuration @0x7fff5fbfec50 Aws::Client::ClientConfiguration
cloudwatch_client @0x7fff5fbfeb60 Aws::CloudWatch::CloudWatchClient
credentials @0x7fff5fbfede0 Aws::Auth::AWSCredentials
cw @0x7fff5fbff1f8 Aws::CloudWatch::CloudWatchClient
cw_remote__ini_filename @0x7fff5fbfef58 QString
cw_remote_ini_file @0x7fff5fbfef20 QFile
cw_remote_ini_json @0x7fff5fbfef60 QString
cw_remote_options @0x7fff5fbff480 Aws::SDKOptions
done false bool
header false bool
options @0x7fff5fbff840 Aws::SDKOptions
outcome @0x7fff5fbfefe0
Aws::Utils::Outcome<Aws::CloudWatch::Model::ListMetricsResult,
Aws::Client::AWSError<Aws::CloudWatch::CloudWatchErrors> >
error @0x7fff5fbff030
Aws::Client::AWSError<Aws::CloudWatch::CloudWatchErrors>
result @0x7fff5fbfefe0 Aws::CloudWatch::Model::ListMetricsResult
success false bool
outcome_error @0x7fff5fbfef80
Aws::Client::AWSError<Aws::CloudWatch::CloudWatchErrors>
m_errorType Aws::CloudWatch::ACCESS_DENIED (15)
Aws::CloudWatch::CloudWatchErrors
m_exceptionName @0x7fff5fbfef88 Aws::String
m_isRetryable false bool
m_message @0x7fff5fbfefa0 Aws::String
m_responseCode Aws::Http::FORBIDDEN (403) Aws::Http::HttpResponseCode
m_responseHeaders @0x7fff5fbfefb8 Aws::Http::HeaderValueCollection
outcome_is_success false bool
region_name @0x7fff5fbfee98 QString
request @0x7fff5fbff6c0 Aws::CloudWatch::Model::ListMetricsRequest
return_code 0 int
```

**Comment by kcrossen** [comment]
Taken one-by-one, each of these problems can be extremely frustrating. It doesn't work? Let's see the logs, where are the logs anyway? I'm sure the answers are all there somewhere, but not together, and not easily found. Unless, of course, you know what you're looking for, and you certainly do, and the person who wrote the docs probably does. Taken together, these problems are likely showstoppers. 

**Beginners need a single, completely self-contained, copy/paste working example with clear directions for finding the diagnostics that the support folks will ask for.**

It's the exact opposite of rocket science. If a reasonably intelligent and computer-savvy admin assistant can't figure it out, perhaps the doc writers need some retraining. They need to consider who's the audience for "getting started", and what do they already know. Nothing, right? Almost by definition.

**Comment by kcrossen** [comment]
The working application is posted here:
https://github.com/kcrossen/CloudWatch_Remote_Monitor/tree/master/Source_Code_Qt5_C%2B%2B

Three different versions, Python/Kivy, Python/PySide2-5.12.2, and C++/Qt5.12.2.

**Comment by singku** [comment]
Thanks Ken, I will direct these samples to the example team.
https://github.com/awsdocs/aws-doc-sdk-examples
