### ISSUE TITLE
HttpClientTest.TestRandomURLMultiThreaded test failure on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by lalit-g-deepr** [aws/aws-sdk-cpp#1486]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Linux Ubuntu bionic 18.04 LTS

**Describe the question**
I am using AWS_SDK_VERSION_STRING "1.8.62". I was having problem in making http request while i am using sns client publish method. The crash occurs after random number of successful publish call but it occurs certainly. I was suggested that i should recompile c++ aws sdk. SDK got compiled successfully but i get error in tests. 2 tests are failed 

/home/{localuser}/Desktop/github/aws-sdk-cpp/aws-cpp-sdk-core-tests/utils/crypto/SymmetricCiphersTest.cpp:696: Failure
[build] Value of: *cipherDe
[build]   Actual: true
[build] Expected: false

[build] [  FAILED  ] HttpClientTest.TestRandomURLMultiThreaded (40081 ms)
[build] [ RUN      ] HttpClientTest.TestRandomURL
[build] [       OK ] HttpClientTest.TestRandomURL (20020 ms)
[build] [----------] 2 tests from HttpClientTest (60101 ms total)

suggest me possible fixes for these test failures. I have gone through the developers document and i have installed essential binaries. I have curl of version 7.72.0 19-08-2020 and openSSL 1.1.1h 22-09-2020, GCC 9.3.0

**Logs/output**
If applicable, add logs or error output.

[build] [==========] 377 tests from 67 test cases ran. (67391 ms total)
[build] [  PASSED  ] 375 tests.
[build] [  FAILED  ] 2 tests, listed below:
[build] [  FAILED  ] HttpClientTest.TestRandomURLMultiThreaded
[build] [  FAILED  ] AES_GCM_TEST.AES_GCM_256_KAT_1
[build] 
[build]  2 FAILED TESTS
[build] aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/build.make:814: recipe for target 'aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests' failed
[build] CMakeFiles/Makefile2:822: recipe for target 'aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all' failed
[build] Makefile:148: recipe for target 'all' failed
[build] make[2]: *** [aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests] Error 1
[build] make[2]: *** Deleting file 'aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests'
[build] make[1]: *** [aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all] Error 2
[build] make: *** [all] Error 2

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by Ri0n** [comment]
I also see this with 1.8.63
```
[ RUN      ] HttpClientTest.TestRandomURLMultiThreaded
/aws-sdk-cpp-1.8.63/aws-cpp-sdk-core-tests/http/HttpClientTest.cpp:81: Failure
Value of: hasPendingTasks
  Actual: true
Expected: false
[  FAILED  ] HttpClientTest.TestRandomURLMultiThreaded (6463 ms)
```

**Comment by Ri0n** [comment]
It started failing with 1.8.53

**Comment by KaibaLopez** [comment]
hi @lalit-g-deepr and
hmm I have a feeling I've seen this issue before, I'll look into it today.
In the mean time and just in case, is there any chance that you've got some sort of firewall blocking the sdk or bad internet connection? It seems like the test is reaching some timeout.
@Ri0n , just to discard this, what versions are you running this on? (Gcc and curl).

Lastly, and for both of you, It'd help me to know what was the cmake command you used.

**Comment by Ri0n** [comment]
@KaibaLopez, I can't reach that PC right now to check all the versions, but it was on Ubuntu 20.04. And I compiled just transcribestream component.

Bad internet connection? If a unit test anyhow depends on the internet connection has to be removed because it's not a unit test more.

**Comment by KaibaLopez** [comment]
@Ri0n , yea I am not able to reproduce this on my side so shooting in the dark until I can, but you're right, we might have remove it depending on what the root cause is, I was hoping for the firewall being the problem though.

**Comment by Ri0n** [comment]
@KaibaLopez, if you want me to add some debug output and restart the tests, just send me a patch.

**Comment by lalit-g-deepr** [comment]
@KaibaLopez sorry for late reply there was medical emergency so i was unable to reach my work PC and i can't get access to github from local. I also think this is some networking issue can you tell which ports needs to be opened and give me your test machine iptables if possible. Thanks

**Comment by Ri0n** [comment]
Once again. A unit test should not depend on any network conditions. If this is the case the unit test has to be removed/rewritten.

@lalit-g-deepr I suggest to just disable unit tests via cmake parameter till it's fixed.

**Comment by lalit-g-deepr** [comment]
@Ri0n It is ok but how would be able to use some functionality which would depend upon that unit test. At that time we might not have clear idea why that one is failing. 
@KaibaLopez I have one more error apart from multithread please look into that one also. this one **/home/{localuser}/Desktop/github/aws-sdk-cpp/aws-cpp-sdk-core-tests/utils/crypto/SymmetricCiphersTest.cpp:696: Failure**

**Comment by Ri0n** [comment]
@lalit-g-deepr it didn't fail before because the test was added just recently. nothing was tested before.

**Comment by lalit-g-deepr** [comment]
@Ri0n I agree but  I have gone through the test and it seems very normal test case. AWS should pass this test with flying colors, and it is passing on @KaibaLopez machine but for lot of other people it is not passing. through Investigation is required. @KaibaLopez what was the purpose of adding this test and which services would be affected if this test is not passed.

**Comment by DavidUser** [comment]
Same problem here.

**Comment by DavidUser** [comment]
@KaibaLopez try it using docke, and probably you will can reproduce:
```
docker run --rm -it -v $(pwd):/home/app -w /home/app fedora
sudo dnf install libcurl-devel openssl-devel libuuid-devel cmake zlib-devel git g++
mkdir build
cd build
sudo cmake .. -D CMAKE_BUILD_TYPE=[Debug | Release] -D BUILD_ONLY="s3"
make
```

**Comment by sfc-gh-schen** [comment]
Is the issue resolved? I have the same issue on centos 7.

**Comment by lalit-g-deepr** [comment]
some of my other teammates are not having this issue so it might be some issue from user side. I dont know the exact cause but hopefully support should be able to help with necessary setting for this.

**Comment by diiiego83** [comment]
I have the same issue (building with ubuntu 20:04 on wls2:

`#46 174.2 [----------] Global test environment tear-down
#46 174.2 [==========] 378 tests from 67 test cases ran. (40464 ms total)
#46 174.2 [  PASSED  ] 377 tests.
#46 174.2 [  FAILED  ] 1 test, listed below:
#46 174.2 [  FAILED  ] HttpClientTest.TestRandomURLMultiThreaded
#46 174.2 
#46 174.2  1 FAILED TEST
#46 174.2 make[2]: *** [aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/build.make:823: aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests] Error 1
#46 174.2 make[2]: *** Deleting file 'aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests'
#46 174.2 make[1]: *** [CMakeFiles/Makefile2:336: aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all] Error 2
#46 174.2 make: *** [Makefile:149: all] Error 2`

**Comment by jartu** [comment]
Same problem here, also on WSL2:

Commands:
```
sudo apt-get install libcurl4-openssl-dev libssl-dev uuid-dev zlib1g-dev libpulse-dev
cd ~/install
git clone https://github.com/aws/aws-sdk-cpp.git
sudo mkdir sdk_build
cd sdk_build
sudo cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_ONLY="sesv2"
sudo make
```

Error:
```
[----------] Global test environment tear-down
[==========] 378 tests from 67 test cases ran. (38279 ms total)
[  PASSED  ] 377 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] HttpClientTest.TestRandomURLMultiThreaded
```

**Comment by KaibaLopez** [comment]
This has been pretty hard to reproduce, it seems like it is an error on the user side configuration but it's hard to say from just the error messages displayed, can someone who is still seeing this error verify :
* gcc and g++ version being used (make sure cmake is using the correct one in case you have multiple versions installed, remember it has to be 4.9 or higher).
* Slow internet should not be a problem but a firewall blocking the connection would be, for reference this is not a unit test but a services integrations test, and yea we assume you'll have internet connection for them. If you want to simply build then set `-DENABLE_TESTING=OFF` on your cmake command.

**Comment by jartu** [comment]
My gcc and g++ are at version 8.3.0 in my WSL2 and at 6.3.0. on my remote Linux box where I have tried this too. The Linux box succeeds the build and the WSL2 stubbornly keeps failing. 

What can I do to help you investigate the problem? Are you also trying the build on a WSL2 ?

**Comment by jartu** [comment]
I have just gone through the following process to replicate the problem from scratch:
1) Reinstalled "Debian" from Microsoft Store on my Windows 10 machine.
2) Pre-installing some libraries
```
sudo apt install aptitude g++ gcc make git wget autoconf automake
# (I also need a fresh version of cmake so installing like this)
cd ~/install
wget https://cmake.org/files/v3.16/cmake-3.16.0.tar.gz
tar -xzvf cmake-3.16.0.tar.gz
cd cmake-3.16.0
./bootstrap 
make -j$(nproc)
sudo make install
# (end of cmake)
```
3) Installing the AWS C++ SDK
sudo apt-get install libcurl4-openssl-dev libssl-dev uuid-dev zlib1g-dev libpulse-dev
cd ~/install
git clone https://github.com/aws/aws-sdk-cpp.git
cd aws-sdk-cpp/
mkdir sdk_build
cd sdk_build
cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_ONLY="sesv2"
make
```
.... and that ends up with the mentioned error.

I don't think there anything too specific in our corporate network, I have never had a problem with any Internet access from inside the company.

**Comment by howheels** [comment]
I'm hitting this same error on CentOS 7.9.
Host is a VM on ESXi.
* GCC / G++: 9.3.0, built from source
* cmake: 3.18.4, built from source
* aws-cpp-sdk: 1.8.99

I am behind a corporate firewall.

cmake command:
```
/opt/cmake/bin/cmake ../ -DCMAKE_CXX_COMPILER=/opt/gcc/bin/g++ -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="s3"
```

Test failures:
```
/home/username/aws-sdk-cpp/aws-cpp-sdk-core-tests/http/HttpClientTest.cpp:81: Failure
Value of: hasPendingTasks
  Actual: true
Expected: false
[  FAILED  ] HttpClientTest.TestRandomURLMultiThreaded (35925 ms)
```

**Comment by appumistri** [comment]
A workaround for me was to add
`-DAUTORUN_UNIT_TESTS=OFF`

**Comment by cpakkala** [comment]
same issue on NixOS:
gcc: 10.3.0 (compiled)
cmake: 3.19.7 (compiled)
aws-cpp-sdk: 1.8.121

Not behind firewall

**Comment by KaibaLopez** [comment]
Hi, I believe this problem should be fixed as of version 1.9.35 ,
If that is not the case feel free to comment, otherwise I'll be marking this issue for closure (If you don't make it to post here before it closes please open a new issue).

**Comment by domenkozar** [comment]
Still reproducable on 1.9.294 as seen in https://github.com/cachix/devenv/issues/302
