### ISSUE TITLE
aws-sdk-cpp- Compilation Warning

### ISSUE THREAD

**Issue by mohammad-aburadeh** [aws/aws-sdk-cpp#1723]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I'm getting the following compilation warning when compiling the aws-sdk-cpp:

```
aws-sdk-cpp/crt/aws-crt-cpp/source/external/cJSON.cpp: In function 'char* Aws::cJSON_SetValuestring(Aws::cJSON*, const char*)':
aws-sdk-cpp/crt/aws-crt-cpp/source/external/cJSON.cpp:429:16: warning: 'char* strncpy(char*, const char*, size_t)' specified bound depends on the length of the source argument [-Wstringop-overflow=]
         strncpy(object->valuestring, valuestring, strlen(valuestring) + 1);
         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
aws-sdk-cpp/crt/aws-crt-cpp/source/external/cJSON.cpp:427:15: note: length computed here
     if (strlen(valuestring) <= strlen(object->valuestring))
```

**SDK version number**
1.9.71

**Platform/OS/Hardware/Device**
Centos/Redhat 7. 
C/C++ Compiler version: 8.3.1

**Comment by KaibaLopez** [comment]
Hi @mohammad-aburadeh ,
I think this was literally [just fixed](https://github.com/aws/aws-sdk-cpp/commit/8d3d62bdf1d8954212c01195a432993f4090cdea) like yesterday, could you try pulling the latest version of the SDK and see if you still see it? (Make sure, to also update the submodules since this is originated in the crt).

**Comment by mohammad-aburadeh** [comment]
Hi @KaibaLopez, 

I pulled the latest version of the SDK(version 1.9.73) and still I see the same warning. 

Thanks
Mohammad

**Comment by KaibaLopez** [comment]
Hmmm that is odd, can you verify that the change is there? Or what is the new error? Since that precise line was changed there must be a change in the error message.

**Comment by Alilux** [comment]
Bug isn't contained yet.. will be now . Issue tracker though

**Comment by KaibaLopez** [comment]
@Alilux not sure I understand your comment but If you are saying the fix hasn't been merged yet, then that's not it, the fix was merged.
 you can even see the changes in the [cJSON.cpp](https://github.com/aws/aws-sdk-cpp/blob/8d3d62bdf1d8954212c01195a432993f4090cdea/aws-cpp-sdk-core/source/external/cjson/cJSON.cpp) file that no longer has the strncpy that was the root cause of the warning.

**Comment by yanw-bq** [comment]
Hi @KaibaLopez , I can see the fix in [`aws-sdk-cpp/aws-cpp-sdk-core/source/external/cjson/cJSON.cpp`](https://github.com/aws/aws-sdk-cpp/blob/1.9.75/aws-cpp-sdk-core/source/external/cjson/cJSON.cpp), but in [`aws-sdk-cpp/crt/aws-crt-cpp/source/external/cJSON.cpp`](https://github.com/awslabs/aws-crt-cpp/blob/c2d6ffa5597825111cc76ad71ffc6aef664d0f25/source/external/cJSON.cpp), it's still using `strncpy()` in function `char* Aws::cJSON_SetValuestring(Aws::cJSON*, const char*)`, which causes the compilation warning when building aws-crt-cpp.

**Comment by mohammad-aburadeh** [comment]
Hi @KaibaLopez

Bellow is the warning I'm still getting:
```
[ 76%] Building CXX object crt/aws-crt-cpp/CMakeFiles/aws-crt-cpp.dir/source/external/cJSON.cpp.o
/u01/aburadeh/aws-sdk-cpp/crt/aws-crt-cpp/source/external/cJSON.cpp: In function 'char* Aws::cJSON_SetValuestring(Aws::cJSON*, const char*)':
/u01/aburadeh/aws-sdk-cpp/crt/aws-crt-cpp/source/external/cJSON.cpp:429:16: warning: 'char* strncpy(char*, const char*, size_t)' specified bound depends on the length of the source argument [-Wstringop-overflow=]
         strncpy(object->valuestring, valuestring, strlen(valuestring) + 1);
         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/u01/aburadeh/aws-sdk-cpp/crt/aws-crt-cpp/source/external/cJSON.cpp:427:15: note: length computed here
     if (strlen(valuestring) <= strlen(object->valuestring))
         ~~~~~~^~~~~~~~~~~~~
```

To reproduce: 
```
-	git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp
-	cd aws-sdk-cpp
-	git checkout main
-	git pull origin main
-	git submodule update --init –recursive

-	mkdir build
-	cd build
-	cmake ../../aws-sdk-cpp -DBUILD_ONLY="s3" -DCMAKE_BUILD_TYPE=Release -DCURL_LIBRARY=/usr/lib64/libcurl.so.4.3.0 -DCURL_INCLUDE_DIR=/usr/include/ -DCMAKE_C_COMPILER=/opt/rh/devtoolset-8/root/usr/bin/gcc -DCMAKE_CXX_COMPILER=/opt/rh/devtoolset-8/root/usr/bin/g++
-	make

```

**Comment by wps132230** [comment]
Thank you for reporting this issue.
We fixed this issue in SDK for C++, but haven't fixed that in the dependency.
I will submit a PR to `awslabs/aws-crt-cpp` and then upgrade the submodules after PR is merged.

**Comment by KaibaLopez** [comment]
As a workaround while this fix gets merged, you could make the [same changes](https://github.com/aws/aws-sdk-cpp/commit/8d3d62bdf1d8954212c01195a432993f4090cdea) from the fix in 
`aws-sdk-cpp/aws-cpp-sdk-core/source/external/cjson/cJSON.cpp`, locally on your `aws-sdk-cpp/crt/aws-crt-cpp/source/external/cJSON.cpp` file.

**Comment by KaibaLopez** [comment]
Hi,
It seems like these changes were applyed to the crt as well so I am marking this issue for closure, let me know if you are still seeing the problem.
