### ISSUE TITLE
Windows build error

### ISSUE THREAD

**Issue by andyli** [aws/aws-sdk-cpp#248]
Using aws-sdk-cpp 0.13.8 (a17726f4a0214b4c37bad774f0b435f6c2050c00), Visual Studio 14 2015.

A bunch of files generated `error C2220: warning treated as error - no 'object' file generated`. Part of the error messages can be found at https://gist.github.com/andyli/0ef48abf36379ef5ef1e1fe5651dad6d 

BTW, what is your thought on using TravisCI and AppVeyor? From the commit log I notice there is already a CI service in use. However, using TravisCI and AppVeyor will at least have the benefit of seeing the build status of PRs. If you think it's a good idea, I can contribute the initial config.

**Comment by bretambrose** [comment]
Your snippet does not include the actual warnings.

**Comment by andyli** [comment]
Alright, here is the complete logs: https://gist.github.com/andyli/1fc9cb694f538d0d67a8c0f2e8adeed1
I compiled only the S3 module, but similar errors exist for other modules as well.

**Comment by bretambrose** [comment]
This may be related to #235

**Comment by bretambrose** [comment]
What locale is Windows set in on your build machine?

**Comment by JonathanHenson** [comment]
This was fixed in 22b769689e5eaa7bb5e02f2443cd5442e863cf99

**Comment by andyli** [comment]
Sadly, no, this is not fixed and the error is the same as mentioned previously.

Tested with 967318c516dceccf2360ed6059bd6e551155164e, the cmake config log and build log can be found at https://gist.github.com/andyli/e28b7086abb0ffa0e46e20d06a557fdd

FYI, according to `systeminfo`, my locale is:
```
System Locale:             zh-hk;Chinese (Hong Kong SAR)
Input Locale:              en-us;English (United States)
```

Would you merge #260 such that we can workaround the issue and use the sdk for now?

**Comment by JonathanHenson** [comment]
It's UTF8 so your locale shouldn't matter. 
I wonder if your file system has cached some files from previous builds or something. There should be nothing that's not UTF8 anywhere in any of those files now.

Can you try either deleting the repo, pulling head and rebuilding or running -DREGENERATE_CLIENTS="1" with your cmake command?

**Comment by andyli** [comment]
The build result and log were already produced by a clean repo, i.e. a newly cloned one.
Following the instruction at http://stackoverflow.com/a/13464816/267998, I can see that the file *aws-cpp-sdk-s3\source\model\CopyObjectRequest.cpp* is still in ANSI encoding.

**Comment by JonathanHenson** [comment]
That's not really the "encoding" of a file. Files aren't magically tagged with their encoding. That editor is guessing at the encoding based on the data it contains. 

Looking at the repo the files you are having trouble with haven't changed. I need to track down what characters are breaking you and find out why they aren't being caught on the UTF8 pass. If those characters are Wide character formats I'm just going to delete the docs. 

I know my changes yesterday impacted application-auto scaling, can you try building that one?  Just for curiosity.

**Comment by andyli** [comment]
Just tested `cmake . -DENABLE_UNITY_BUILD=ON -DBUILD_ONLY=application-autoscaling`. There is no unicode-related error, but still an error of `no 'object' file generated`. Complete build log is at https://gist.github.com/andyli/94238cecba1810f8242853b7cf0349fc

**Comment by JonathanHenson** [comment]
Ok, I think I know what's happening. We have made sure UTF8 is correctly used, but Msft compilers require a BOM to detect the file encoding. When a locale is used that doesn't assume UTF8 Msft compilers don't know to use UTF8. I'll experiment with adding a BOM to each of the generated files this afternoon and see if that fixes your issue.

**Comment by JonathanHenson** [comment]
Ok, I've added byte order marks to all of the generated files. Could you give it another try with the latest release?

**Comment by andyli** [comment]
It builds correctly now! 0 error for all components. Thanks! :D
