### ISSUE TITLE
Cannot use FORCE_CURL option on Windows with VS2013/Windows Kit 8.1

### ISSUE THREAD

**Issue by Teknogrebo** [aws/aws-sdk-cpp#298]
More of a problem due to windows, but the UUID symbol used in core/utils clashes with a the Windows typedef in prcdce.h

```
ClCompile:
  ub_core.cpp
C:\Program Files (x86)\Windows Kits\8.1\Include\shared\rpcdce.h(101) : error C2872: 'UUID' : ambiguous symbol
        could be 'C:\Program Files (x86)\Windows Kits\8.1\Include\shared\rpcdce.h(77) : GUID UUID'
        or       'T:\branches\arena\dev\common\ThirdParty\aws-sdk\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(33) : Aws::Utils::UUID'


```Our application already uses curl and we don't want to drag in WinHTTP as well.

**Comment by bretambrose** [comment]
Is this with the latest published version (from yesterday)?  I believe this was just fixed in that push.  If not, I will check it this weekend.

**Comment by Teknogrebo** [comment]
It was from a clone of master (tagged 1.0.8 I believe) on Thursday. I guess it's not fixed, unless I'm doing something wrong.

**Comment by bretambrose** [comment]
This has been fixed internally and will show up in our next release (October 4th).

**Comment by JonathanHenson** [comment]
Can you verify your issue has been resolved?

**Comment by Teknogrebo** [comment]
Hi, I can indeed verify that I can build with FORCE_CURL on Windows now.  Thank you very much for the rapid fix :)
