### ISSUE TITLE
EC2 RequestSpotFleet problems

### ISSUE THREAD

**Issue by yasushi-saito** [aws/aws-sdk-cpp#396]
SpotFleetRequestConfigData seems to be serialized wrongly. The below patch fixes the problem.
In addition, SpotFleetRequestConfig.DryRun doesn't seem to have an effect - it creates an SFR whether or not DryRun=true.

```
diff --git a/aws-cpp-sdk-ec2/source/model/SpotFleetLaunchSpecification.cpp b/aws-cpp-sdk-ec2/source/model/SpotFleetLaunchSpecification.cpp
index ae943ddf0..9d660c2a8 100644
--- a/aws-cpp-sdk-ec2/source/model/SpotFleetLaunchSpecification.cpp
+++ b/aws-cpp-sdk-ec2/source/model/SpotFleetLaunchSpecification.cpp
@@ -338,7 +338,7 @@ void SpotFleetLaunchSpecification::OutputToStream(Aws::OStream& oStream, const c
       for(auto& item : m_securityGroups)
       {
         Aws::StringStream securityGroupsSs;
-        securityGroupsSs << location <<  ".item." << securityGroupsIdx++;
+        securityGroupsSs << location <<  ".GroupSet." << securityGroupsIdx++;
         item.OutputToStream(oStream, securityGroupsSs.str().c_str());
       }
   }
@@ -374,7 +374,7 @@ void SpotFleetLaunchSpecification::OutputToStream(Aws::OStream& oStream, const c
       for(auto& item : m_blockDeviceMappings)
       {
         Aws::StringStream blockDeviceMappingsSs;
-        blockDeviceMappingsSs << location <<  ".item." << blockDeviceMappingsIdx++;
+        blockDeviceMappingsSs << location <<  ".BlockDeviceMapping." << blockDeviceMappingsIdx++;
         item.OutputToStream(oStream, blockDeviceMappingsSs.str().c_str());
       }
   }
@@ -394,7 +394,7 @@ void SpotFleetLaunchSpecification::OutputToStream(Aws::OStream& oStream, const c
       for(auto& item : m_networkInterfaces)
       {
         Aws::StringStream networkInterfacesSs;
-        networkInterfacesSs << location <<  ".item." << networkInterfacesIdx++;
+        networkInterfacesSs << location <<  ".NetworkInterfaceSet." << networkInterfacesIdx++;
         item.OutputToStream(oStream, networkInterfacesSs.str().c_str());
       }
   }
diff --git a/aws-cpp-sdk-ec2/source/model/SpotFleetRequestConfigData.cpp b/aws-cpp-sdk-ec2/source/model/SpotFleetRequestConfigData.cpp
index d3ba49dc3..81ab3529a 100644
--- a/aws-cpp-sdk-ec2/source/model/SpotFleetRequestConfigData.cpp
+++ b/aws-cpp-sdk-ec2/source/model/SpotFleetRequestConfigData.cpp
@@ -269,7 +269,7 @@ void SpotFleetRequestConfigData::OutputToStream(Aws::OStream& oStream, const cha
       for(auto& item : m_launchSpecifications)
       {
         Aws::StringStream launchSpecificationsSs;
-        launchSpecificationsSs << location <<  ".item." << launchSpecificationsIdx++;
+        launchSpecificationsSs << location <<  ".LaunchSpecifications." << launchSpecificationsIdx++;
         item.OutputToStream(oStream, launchSpecificationsSs.str().c_str());
       }
   }
```

**Comment by bretambrose** [comment]
There are a number of problems with the EC2 client which should get fixed up in the next week or so.

**Comment by bretambrose** [comment]
This should be fixed with yesterday's release.  Let us know if you have further EC2 issues; it has a huge API and the code generation is delicate and kind of messy, so I wouldn't be surprised if there are still some hidden problems.

**Comment by yasushi-saito** [comment]
I'm still seeing the same problem with 1.0.51. Applying a similar patch solves the problem.

**Comment by bretambrose** [comment]
It looks like I didn't catch all the cases.  I'll go over this again sometime this week.

**Comment by JonathanHenson** [comment]
I just fixed this. I'll be pushing it out shortly.
